name: example
description: A flutter_form_builder example project.

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_form_builder:
    path: ../
  widget_with_codeview: ^1.0.3
  cupertino_icons: any

dependency_overrides:
  modal_bottom_sheet: ^0.2.1+1-dev

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation:

flutter:
  uses-material-design: true
  assets:
    - lib/sources/
