name: flutter_form_builder
description: This package helps in creation of forms in Flutter by removing the boilerplate code, reusing validation, react to changes, and collect final user input.
version: 10.0.1
repository: https://github.com/flutter-form-builder-ecosystem/flutter_form_builder
homepage: https://github.com/flutter-form-builder-ecosystem
issue_tracker: https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/issues
topics:
  - form
funding:
  - https://opencollective.com/flutter-form-builder-ecosystem

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  # This version would be max, the same version used on flutter_localizations
  # https://github.com/flutter/flutter/blob/17025dd88227cd9532c33fa78f5250d548d87e9a/packages/flutter_localizations/pubspec.yaml#L14
  intl: ">=0.19.0 <0.21.0"

dev_dependencies:
  flutter_lints: ">=5.0.0 <7.0.0"
  flutter_test:
    sdk: flutter
