name: flutter_form_builder
description: Package to build Material Form with fields like TextField, DropDown, Switches etc. with ability to create custom FormFields and composability and reuse validation functions.
version: 3.6.1
author: Danvick Miller <danvickmiller@gmail.com>
homepage: https://github.com/danvick/flutter_form_builder

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_typeahead: ^1.7.0
  intl: ^0.16.0
  sy_flutter_widgets: ^0.1.4
  flutter_chips_input: ^1.6.0
  datetime_picker_formfield: ^1.0.0-pre.5
  # signature: ^2.0.0 - Doesn't implement onChanged, submitted PR. Meanwhile using local clone with onChanged
  validators: ^2.0.0+1
  date_range_picker: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.5.3

flutter:
