name: flutter_form_builder
description: Package to build Material Form with fields like TextField, DropDown, Switches etc. with ability to create custom FormFields and composability and reuse validation functions.
version: 4.0.0-beta.5
homepage: https://github.com/danvick/flutter_form_builder

environment:
  sdk: '>=2.6.0 <3.0.0'
  flutter: '>=1.20.1'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  country_code_picker: ^1.4.0
  country_pickers: ^1.3.0
  date_range_picker: ^1.0.6
  datetime_picker_formfield: ^1.0.0
  flutter_colorpicker: ^0.3.4
  flutter_chips_input: ^1.9.3
  flutter_touch_spin: ^1.0.1
  flutter_typeahead: ^1.8.8
  image_picker: ^0.6.7+7
  image_picker_for_web: ^0.1.0+1
  intl: ^0.16.1
  phone_number: ^0.6.2+4
  rating_bar: ^0.2.0
  signature: ^3.2.0
  validators: ^2.0.1
  flutter_datetime_picker: ^1.4.0
  google_maps_flutter: ^0.5.31
  dropdown_search: ^0.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  pedantic: ^1.9.0
  intl_translation:
  # flutter pub pub run intl_translation:extract_to_arb --output-dir=lib/l10n lib/localization/form_builder_localizations.dart
  #flutter pub pub run intl_translation:generate_from_arb --output-dir=lib/l10n --no-use-deferred-loading lib/localization/form_builder_localizations.dart lib/l10n/intl_*.arb

flutter:
