name: flutter_form_builder
description: This package helps in creation of forms in Flutter by removing the boilerplate code, reusing validation, react to changes, and collect final user input.
version: 9.0.0-dev.2
repository: https://github.com/flutter-form-builder-ecosystem/flutter_form_builder
issue_tracker: https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/issues
homepage: https://github.com/flutter-form-builder-ecosystem
funding: 
  - https://opencollective.com/flutter-form-builder-ecosystem

environment:
  sdk: ">2.19.0 <3.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  collection: ^1.17.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
