name: flutter_form_builder
description: Package to build Material Form with fields like TextField, DropDown, Switches etc. with ability to create custom FormFields and composability and reuse validation functions.
version: 4.0.0-alpha.2
homepage: https://github.com/danvick/flutter_form_builder

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_typeahead: ^1.8.3
  intl: ^0.16.1
  flutter_chips_input: ^1.8.3
  datetime_picker_formfield: ^1.0.0
  flutter_colorpicker: ^0.3.4
  signature: ^3.1.1
  validators: ^2.0.0+1
  date_range_picker: ^1.0.6
  flutter_touch_spin: ^1.0.1
  image_picker: ^0.6.7+2
  rating_bar: ^0.2.0
  country_pickers: ^1.3.0
  phone_number: ^0.6.2+3
  group_radio_button: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.14.1
  pedantic: ^1.9.0

flutter:
