name: Base (beta)

on:
  schedule:
    - cron: '0 0 */15 * *' # Runs every 15 days for verifying changes on Flutter beta channel
  push:
    branches: [beta]
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-*'

  pull_request:
    branches: [beta]

  workflow_dispatch:

# This ensures that previous jobs for the PR are canceled when PR is updated
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: flutter-form-builder-ecosystem/.github/.github/workflows/minimal-quality.yaml@main
    with:
      codecov-name: flutter_form_builder
      enable-fix-tests: true
      fvm-flavor: beta
  example:
    uses: flutter-form-builder-ecosystem/.github/.github/workflows/build-examples.yaml@main
    with:
      fvm-flavor: beta


  deployment:
    permissions:
      id-token: write
    uses: flutter-form-builder-ecosystem/.github/.github/workflows/deployment.yaml@main
    if: ${{ github.ref_type == 'tag' }}
    needs: [build, example]
